#!/usr/bin/env zsh

# replace (expanded $HOME) with ~ just in case it changes
local dotfiles="${${0:a:h}/$HOME/~}"

local zshrc_template="source ${dotfiles}/zsh/zshrc"
if ! grep -q "$zshrc_template" ~/.zshrc 2> /dev/null; then
    mv ~/.zshrc{,.old.${(%):-%D{%F.%T}}} 2> /dev/null
    echo "$zshrc_template" > ~/.zshrc
fi

local zshenv_template="source ${dotfiles}/zsh/zshenv"
if ! grep -q "$zshenv_template" ~/.zshenv 2>/dev/null; then
    mv ~/.zshenv{,.old.${(%):-%D{%F.%T}}} 2> /dev/null
    echo "$zshenv_template" > ~/.zshenv
fi

local initvim_location=~/.config/nvim/init.vim
local initvim_template="source ${dotfiles}/nvim/init.vim"
mkdir -p "${initvim_location:h}"
if ! grep -q "$initvim_template" "$initvim_location" 2> /dev/null; then
    mv ${initvim_location}{,.old.${(%):-%D{%F.%T}}} 2> /dev/null
    echo "$initvim_template" > $initvim_location
fi
