#!/usr/bin/env zsh

# replace (expanded $HOME) with ~ just in case it changes
local dotfiles="${${0:a:h}/$HOME/~}"
cd ${~dotfiles}

setopt extended_glob
mv external/fast-syntax-highlighting/{→chroma,chroma}
local zsh_deps=(
  external/powerlevel10k/{*.zsh-theme,internal/*.zsh}
  external/fast-syntax-highlighting/{fast*~*.zwc,.fast*~*.zwc,**/*.ch,**/*.zsh}
)
for f in $zsh_deps; do
  if [[ ! $f.zwc -nt $f ]]; then
    zcompile -R -- $f.zwc $f && echo "compiled $f"
  fi
done
mv external/fast-syntax-highlighting/{chroma,→chroma}

local zshrc_template="source ${dotfiles}/zsh/zshrc"
if ! grep -q "$zshrc_template" ~/.zshrc 2> /dev/null; then
  mv ~/.zshrc{,.old.${(%):-%D{%F.%T}}} 2> /dev/null
  echo "$zshrc_template" > ~/.zshrc
  echo "sourced zsh/zshrc"
fi

local zshenv_template="source ${dotfiles}/zsh/zshenv"
if ! grep -q "$zshenv_template" ~/.zshenv 2>/dev/null; then
  mv ~/.zshenv{,.old.${(%):-%D{%F.%T}}} 2> /dev/null
  echo "$zshenv_template" > ~/.zshenv
  echo "sourced zsh/zshenv"
fi

local initvim_location=~/.config/nvim/init.vim
local initvim_template="source ${dotfiles}/nvim/init.vim"
mkdir -p "${initvim_location:h}"
if ! grep -q "$initvim_template" "$initvim_location" 2> /dev/null; then
  mv ${initvim_location}{,.old.${(%):-%D{%F.%T}}} 2> /dev/null
  echo "$initvim_template" > $initvim_location
  echo "sourced nvim/init.vim"
fi

# TODO: reduce repetition here?
local jjconfig_location=~/.config/jj/config.toml
mkdir -p "${jjconfig_location:h}"
if [[ $(readlink -e $jjconfig_location) != ${0:a:h}/jj/config.toml ]]; then
  mv ${jjconfig_location}{,.old.${(%):-%D{%F.%T}}} 2> /dev/null
  # use relative links, in case $HOME changes location
  ln -sr ${0:a:h}/jj/config.toml $jjconfig_location
  echo "symlinked jj/config.toml"
fi

local gitconfig_location=~/.config/git/config
mkdir -p "${gitconfig_location:h}"
if [[ $(readlink -e $gitconfig_location) != ${0:a:h}/git/config ]]; then
  mv ${gitconfig_location}{,.old.${(%):-%D{%F.%T}}} 2> /dev/null
  ln -sr ${0:a:h}/git/config $gitconfig_location
  echo "symlinked git/config"
fi
