# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

local dotfiles="${0:a:h:h}"
local external="${dotfiles}/external"
local zdotfiles="${dotfiles}/zsh"

# BEGIN: modification of external/ohmyzsh/oh-my-zsh.sh
# SPDX-License-Identifier: MIT
ZSH_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/zsh"
# Create cache and completions dir and add to $fpath
mkdir -p "$ZSH_CACHE_DIR/completions"
(( ${fpath[(Ie)$ZSH_CACHE_DIR/completions]} )) || fpath=("$ZSH_CACHE_DIR/completions" $fpath)
# mcpower: all other fpath modifications are pointless...
# Load all stock functions (from $fpath files) called below.
autoload -U compaudit compinit zrecompile
# Figure out the SHORT hostname
if [[ "$OSTYPE" = darwin* ]]; then
  # macOS's $HOST changes with dhcp, etc. Use LocalHostName if possible.
  SHORT_HOST=$(scutil --get LocalHostName 2>/dev/null) || SHORT_HOST="${HOST/.*/}"
else
  SHORT_HOST="${HOST/.*/}"
fi
# Save the location of the current completion dump file.
ZSH_COMPDUMP="$ZSH_CACHE_DIR/zcompdump-${SHORT_HOST}-${ZSH_VERSION}"
# Construct zcompdump metadata
local zcompdump_revision="#dotfiles revision: $(builtin cd -q "$dotfiles"; git rev-parse HEAD 2>/dev/null)"
local zcompdump_fpath="#fpath: $fpath"
# Delete the zcompdump file if zcompdump metadata changed
if ! command grep -q -Fx "$zcompdump_revision" "$ZSH_COMPDUMP" 2>/dev/null \
   || ! command grep -q -Fx "$zcompdump_fpath" "$ZSH_COMPDUMP" 2>/dev/null; then
  command rm -f "$ZSH_COMPDUMP"
  zcompdump_refresh=1
fi
source "$external/ohmyzsh/lib/compfix.zsh"
# Load only from secure directories
compinit -i -d "$ZSH_COMPDUMP"
# If completion insecurities exist, warn the user
handle_completion_insecurities &|
# Append zcompdump metadata if missing
if (( $zcompdump_refresh )) \
  || ! command grep -q -Fx "$zcompdump_revision" "$ZSH_COMPDUMP" 2>/dev/null; then
  # Use `tee` in case the $ZSH_COMPDUMP filename is invalid, to silence the error
  # See https://github.com/ohmyzsh/ohmyzsh/commit/dd1a7269#commitcomment-39003489
  tee -a "$ZSH_COMPDUMP" &>/dev/null <<EOF

$zcompdump_revision
$zcompdump_fpath
EOF
fi
unset zcompdump_revision zcompdump_fpath zcompdump_refresh
# zcompile the completion dump file if the .zwc is older or missing.
if command mkdir "${ZSH_COMPDUMP}.lock" 2>/dev/null; then
  zrecompile -q -p "$ZSH_COMPDUMP"
  command rm -rf "$ZSH_COMPDUMP.zwc.old" "${ZSH_COMPDUMP}.lock"
fi
for lib_file in "$external"/ohmyzsh/lib/*.zsh; do
  source "$lib_file"
done
source "$external/ohmyzsh/plugins/fzf/fzf.plugin.zsh"
# set completion colors to be the same as `ls`, after theme has been loaded
[[ -z "$LS_COLORS" ]] || zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
# END: modification of external/ohmyzsh/oh-my-zsh.sh

source "${external}/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh"
ZSH_AUTOSUGGEST_MANUAL_REBIND=1
source "${external}/zsh-autosuggestions/zsh-autosuggestions.zsh"
source "${external}/powerlevel10k/powerlevel10k.zsh-theme"
source "${external}/zsh-async/async.zsh"
source "${zdotfiles}/p10k.zsh"

export PNPM_HOME=~/.local/share/pnpm
# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path
path=(
  ~/bin
  ~/.local/bin
  ~/.cargo/bin
  $PNPM_HOME
  $path
)

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'
[[ ! -f ~/.env.zsh ]] || source ~/.env.zsh

alias vim='nvim'
# this assumes GNU coreutils, can't be bothered supporting others
# put directories first, then sort dotfiles > uppercase > lowercase
alias ls="${aliases[ls]:-ls} --group-directories-first -v"

# WSL-only functions
if [[ "$(uname -r)" = *icrosoft* ]]; then
  function exp() {
    explorer.exe ${1:-.}
  }
fi

# old competitive programming functions, rewritten in zsh
function __run() {
  emulate -LR zsh
  setopt nullglob
  setopt clobber
  local source_pattern="${1}"
  local compile_command=(${(z)2})
  local run_command="${3}"

  local source_file=$(ls -t ${~source_pattern} | head -n1)
  $compile_command $source_file || return

  for input_file in *.in; do
    echo --- $source_file $input_file
    local expected_file=(${input_file%in}[ao]??)
    local output_file=$(mktemp --suffix=.run_out)
    {
      $run_command $source_file < $input_file > $output_file
      if [[ $? -ne 0 ]] then
        echo "!!! RE (exit code $?) !!!"
        cat $output_file
        continue
      fi
      if (( ${#expected_file[@]} > 0 )); then
        local diff_file=$(mktemp --suffix=.run_diff)
        {
          if ! diff -y $output_file $expected_file > $diff_file; then
            echo "!!! WA !!!"
            cat $diff_file
          fi
        } always {
          command rm $diff_file
        }
      else
        echo "!!! no expected output !!!"
        cat $output_file
      fi
    } always {
      command rm $output_file
    }
  done
}
function run() {
  __run \
    "*.c*" \
    "g++ -g -std=c++11 -Wall -Wextra -Wconversion -Wshadow -Wfatal-errors -fsanitize=undefined -o sol" \
    "./sol"
}
function runfast() {
  __run \
    "*.c*" \
    "g++ -g -std=c++11 -Wall -Wextra -Wconversion -Wshadow -Wfatal-errors -O3 -o sol" \
    "./sol"
}
function runpy() {
  __run "*.py" "true" "python3"
}
function runpypy() {
  __run "*.py" "true" "pypy3"
}
