# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

local dotfiles="${0:a:h:h}"
local external="${dotfiles}/external"
local zdotfiles="${dotfiles}/zsh"

# BEGIN: modification of external/ohmyzsh/oh-my-zsh.sh
# SPDX-License-Identifier: MIT

# Used in a lot of ohmyzsh scripts.
ZSH_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/zsh"
# $ZSH_CACHE_DIR/completions should be used to store completions that compinit
# can pick up.
mkdir -p "$ZSH_CACHE_DIR/completions"
fpath=("$zdotfiles/functions" "$ZSH_CACHE_DIR/completions" $fpath)

autoload -U compaudit compinit zrecompile
# ohmyzsh uses the zsh version + host to avoid "subtle problems that happen when
# people upgrade ZSH or use NFS mounted home directories" from a 2013 commit:
# https://github.com/ohmyzsh/ohmyzsh/commit/d2fe03d7
# The upgrade problem was solved back in 2004:
# https://github.com/zsh-users/zsh/commit/78da7d87
# I hope I will never use NFS mounted home directories, so we can safely ignore
# the host too.
ZSH_COMPDUMP="$ZSH_CACHE_DIR/zcompdump"
# ohmyzsh adds the OMZ Git revision and the contents of $fpath to the compdump,
# and compares against it every time this is run to check if there are any
# updates. This is very overkill, especially as zsh automatically uses the
# number of files as a proxy for when this changes. Skip all of that.

# Explicitly use -i here to ignore insecure directories. If we omitted -i and
# there were insecure directories, compinit would ask for input - slowing down
# p10k's instant prompt.
compinit -i -d "$ZSH_COMPDUMP"
# Warn the user after the fact if there were insecure directories.
source "$external/ohmyzsh/lib/compfix.zsh"
handle_completion_insecurities &|

# zcompile the completion dump file if the .zwc is older or missing.
# Use a lockfile to prevent races, see
# https://github.com/ohmyzsh/ohmyzsh/issues/11341
if zrecompile -t -q -p "$ZSH_COMPDUMP" && \
   command mkdir "${ZSH_COMPDUMP}.lock" 2>/dev/null; then
  zrecompile -q -p "$ZSH_COMPDUMP"
  # zrecompile leaves around a .old file which ohmyzsh deletes. Don't bother
  # deleting it here.
  command rmdir "${ZSH_COMPDUMP}.lock"
fi

local omz_libs=(
  # async_prompt          # Replaced by async.zsh
  # bzr                   # I use p10k for prompt
  clipboard               # Reasonable unified clipboard aliases
  # cli                   # Opinionated CLI for omz features I don't use
  # compfix               # Sourced above
  completion              # Reasonable defaults/setopts
  # correction            # I don't use correction
  # diagnostics           # Only used for debugging
  directories             # Reasonable setopts but a lot of opinionated aliases…
  functions               # A LOT of opinionated functions, some used below…
  # git                   # I use p10k for prompt
  grep                    # Reasonable defaults/aliases
  history                 # Reasonable defaults, plus an opinionated `omz_history`…
  key-bindings            # Good defaults
  misc                    # Reasonable defaults…? Uses `env_default` from `functions`
  # nvm                   # I use p10k for prompt
  # prompt_info_functions # I use p10k for prompt
  # spectrum              # Redundant with `colors`, loaded in `theme-and-appearance`
  termsupport             # Sets terminal titles. Uses `omz_urlencode` from `functions`
  theme-and-appearance    # Sets diff / ls colours, plus random exports
  # vcs_info              # I use p10k for prompt
)
for lib in $omz_libs; do
  source "$external/ohmyzsh/lib/$lib.zsh"
done
source "$external/ohmyzsh/plugins/fzf/fzf.plugin.zsh"

# set completion colors to be the same as `ls`, after theme has been loaded
[[ -z "$LS_COLORS" ]] || zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
# END: modification of external/ohmyzsh/oh-my-zsh.sh

source "${external}/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh"
ZSH_AUTOSUGGEST_MANUAL_REBIND=1
source "${external}/zsh-autosuggestions/zsh-autosuggestions.zsh"
source "${external}/powerlevel10k/powerlevel10k.zsh-theme"
source "${external}/zsh-async/async.zsh"
source "${zdotfiles}/p10k.zsh"

export PNPM_HOME=~/.local/share/pnpm
# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path
path=(
  ~/bin
  ~/.local/bin
  ~/.cargo/bin
  $PNPM_HOME
  $path
)

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'
[[ ! -f ~/.env.zsh ]] || source ~/.env.zsh

alias vim='nvim'
# this assumes GNU coreutils, can't be bothered supporting others
# put directories first, then sort dotfiles > uppercase > lowercase
alias ls="${aliases[ls]:-ls} --group-directories-first -v"

# WSL-only functions
if [[ "$(uname -r)" = *icrosoft* ]]; then
  function exp() {
    explorer.exe ${1:-.}
  }
fi

# old competitive programming functions, rewritten in zsh
autoload __run
function run() {
  __run \
    "*.c*" \
    "g++ -g -std=c++11 -Wall -Wextra -Wconversion -Wshadow -Wfatal-errors -fsanitize=undefined -o sol" \
    "./sol"
}
function runfast() {
  __run \
    "*.c*" \
    "g++ -g -std=c++11 -Wall -Wextra -Wconversion -Wshadow -Wfatal-errors -O3 -o sol" \
    "./sol"
}
function runpy() {
  __run "*.py" "true" "python3"
}
function runpypy() {
  __run "*.py" "true" "pypy3"
}
